---
title: "p8105_hw6_jl6325"
author: "Jianing Liu"
date: "2023-12-03"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(modelr)
library(mgcv)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Not grade

## Problem 2

Get the Central Park dataset first.
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Set bootstrap
```{r}
set.seed(1)

fit <-
  lm(tmax ~ tmin + prcp, data = weather_df)

boot_sample <-
  function(df) {
    sample_frac(df, replace = TRUE)
  }

boot_straps <-
  weather_df |>
  modelr::bootstrap(n = 5000) |>
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
    result1 = map(models, broom::tidy),
    result2 = map(models, broom::glance)
  ) |>
  select(-strap, -models)
```

Get r_square
```{r}
r_square <-
  boot_straps |>
  select(result2, .id) |>
  unnest(result2) |>
  select(r.squared, .id)
```

Plot r_square
```{r}
r_square_plot <-
  r_square |>
  ggplot(aes(x = r.squared)) +
  geom_histogram()

r_square_plot
```


Plot estimates
```{r}
log_beta = 
  boot_straps |>
  select(result1, .id) |>
  unnest(result1) |>
  select(.id, term, estimate) |>
  mutate(term = ifelse(term == "tmin", "beta_1",
                       ifelse(term == "prcp", "beta_2", term))) |>
  pivot_wider(names_from = term,
              values_from = estimate) |>
  mutate(log_betas = log(beta_1 * beta_2))

log_beta_plot <-
  log_beta |>
  ggplot(
    aes(x = log_betas)
  ) +
  geom_histogram()

log_beta_plot
```

95%CI for r_square
```{r}
r_square_95CI <-
  boot_straps |>
  unnest(result1, result2) |>
  summarise(
    lowertile = quantile(r.squared, 0.025),
    uppertile = quantile(r.squared, 0.975)
  ) |>
  knitr::kable()
r_square_95CI
```



95%CI for log_betas
```{r}
lowertile <- quantile(log_beta$log_betas, 0.025, na.rm = TRUE)
uppertile <- quantile(log_beta$log_betas, 0.975, na.rm = TRUE)
confidence_interval_log <- c(lowertile, uppertile)
confidence_interval_log
```

95%CI for r_square: (0.8885495,	0.9406812)

95%CI for log_betas: (-8.981559, -4.601673)

## Problem3
Read dataset
```{r}
birthweight = 
  read_csv(file = "data/birthweight.csv") |> 
  janitor::clean_names() |> 
  drop_na() |> 
  mutate(
    babysex = recode(
      babysex,
      "1" = "Male",
      "2" = "Female"
    ),
    babysex = as.factor(babysex),
    frace = recode(
      frace,
      "1" = "White", 
      "2" = "Black", 
      "3" = "Asian", 
      "4" = "Puerto_Rican", 
      "8" = "Other", 
      "9" = "Unknown"
    ),
    frace = as.factor(frace),
    mrace = recode(
      mrace,
      "1" = "White", 
      "2" = "Black", 
      "3" = "Asian", 
      "4"="Puerto_Rican", 
      "8"="Other"
    ),
    mrace = as.factor(mrace),
    malform = recode(
      malform,
      "0" = "Absent",
      "1" = "Present"
    ),
    malform = as.factor(malform)
    )
```



